model: unconditional
diffusion_config: diffusion_small_config
normalization: mean
use_features: False
use_lags: False
dataset: synthetic_data/dw_1.csv
freq: H
context_length: 312 # 360 for `D`
prediction_length: 50 # 30 for `D`
lr: 1.e-3
init_skip: False
gradient_clip_val: 0.5
max_epochs: 1000
num_batches_per_epoch: 128
batch_size: 7500
# Used only in callback,
# the final evaluation uses 100 samples
num_samples: 8
sampler: ddpm
sampler_params:
  guidance: quantile
  scale: 2
use_validation_set: True
eval_every: 50
device: cuda:0
setup: forecasting



'''dataset:
  name: m4
  data_path: synthetic_data/dw_1.csv
  seq_len: 7500

model:
  input_dim: 1
  seq_len: 7500
'''